Allow installing `yarn` via `corepack` on Debian-based systems, too
devcontainers/features pull request #1009
Opened 2024-06-19 09:24 UTC by hoechenberger

The default behavior remains unchanged, but users can now opt-out from the APT-based installation to get the latest `yarn` via `corepack`.

Closes #1004

2024-06-19 19:11 UTC, samruddhikhandale requested changes
This makes sense, thanks! 

Left couple of comments

2024-06-19 19:11 UTC, samruddhikhandale commented on src/node/devcontainer-feature.json
> +            "description": "Whether to install yarn globally via APT on Debian-based systems (Debian, Ubuntu). If false, will set up yarn via corepack. This setting is ignored on other Linux images,
```suggestion
            "description": "On Debian & Ubuntu systems, you can choose whether to install Yarn globally via APT. If this option is set to false, Yarn will be set up via Corepack instead. This setting does not apply to other Linux distributions, where Yarn is always installed using Corepack."
```

2024-06-19 19:11 UTC, samruddhikhandale commented on src/node/devcontainer-feature.json
> +        "yarnFromApt": {
```suggestion
        "installYarnUsingApt": {
```

2024-06-19 19:11 UTC, samruddhikhandale commented on src/node/install.sh
> +export YARN_FROM_APT="${YARNFROMAPT:-true}"  # only concerns Debian-based systems
Need to update post rename the Feature option.

2024-06-19 19:11 UTC, samruddhikhandale commented on src/node/install.sh
> +    if [ "${ADJUSTED_ID}" = "debian" ] && [ "${YARN_FROM_APT}" = "true" ]; then
Can we add a test to validate these changes? Thanks!

2024-06-19 21:01 UTC, hoechenberger commented
@samruddhikhandale I believe I've addressed all your comments. Unfortunately I currently cannot run the test case locally, so we'll have to rely on the CI output

2024-06-20 08:12 UTC, hoechenberger commented on test/node/debian_yarn_from_corepack.sh
> +# Corepack provides shims for package managers like yarn. When yarn is invoked by the "yarn"
```suggestion
# Corepack provides shims for package managers like yarn. When yarn is invoked via the "yarn"
```

2024-06-20 21:06 UTC, samruddhikhandale approved these changes
Looks good, thanks!

2024-06-20 21:07 UTC, samruddhikhandale approved these changes

2024-06-20 21:07 UTC, merged