Rust: add the option to install additional targets
devcontainers/features pull request #1033
Opened 2024-07-07 03:12 UTC by yaleman

Fixes #1032

* Adds the "targets" input
* Did some shellcheck-based linting of the shell script
* Added a test for the new option

2024-07-07 03:15 UTC, yaleman commented
@microsoft-github-policy-service agree

2024-07-09 22:59 UTC, samruddhikhandale requested changes
Thanks for taking the time in contributing this PR. The new Feature option addition makes sense to me and will be very helpful.

Left some minor comments.
Also, thanks for optimizing the current script 🙏

2024-07-09 22:59 UTC, samruddhikhandale commented on src/rust/devcontainer-feature.json
> +    "version": "1.1.4",
```suggestion
    "version": "1.2.0",
```

Can we bump minor version as we are adding a new Feature option?

2024-07-09 22:59 UTC, samruddhikhandale commented on src/rust/devcontainer-feature.json
> +            "description": "Comma-delimited list of additional Rust targets to install.",
```suggestion
            "description": "Optional comma separated list of additional Rust target to install",
```

2024-07-09 22:59 UTC, samruddhikhandale commented on src/rust/install.sh
> +fi
```suggestion
if [ -n "${RUSTUP_TARGETS}" ]; then
    IFS=',' read -ra targets <<< "${RUSTUP_TARGETS}"
    for target in "${targets[@]}"; do
        echo "Installing additional Rust target $target"
        rustup target add "$target" 2>&1
    done
fi
```

Nit: Suggestion (untested)

2024-07-10 18:56 UTC, samruddhikhandale approved these changes
Wonderful, thank you ✨

2024-07-10 18:56 UTC, merged