Use new CDN for dotnet builds
devcontainers/features pull request #1230
Opened 2024-12-28 01:14 UTC by sliekens

The `azureedge.net` domain might stop working as detailed in https://github.com/dotnet/core/issues/9671

Changes in this PR:

- **dotnet**: update the logic to determine the latest version
- **dotnet and oryx**: copy latest dotnet-install script from
  https://github.com/dotnet/install-scripts/blob/main/src/dotnet-install.sh
  (Normally this happens automatically by a GitHub Action, but there is a sense of urgency here, so I did it manually)

Additional context
- https://build5nines.com/retirement-of-azureedge-net-dns-edg-io-business-closure-and-what-you-need-to-know/

2024-12-28 20:08 UTC, sliekens commented
Cc @samruddhikhandale @Chuxel

2025-01-07 10:01 UTC, chrmarti requested changes
Great, thanks for the PR! Left a few questions.

2025-01-07 10:01 UTC, chrmarti commented on src/dotnet/scripts/vendor/dotnet-install.sh
> +        sanitized_redirect_url=$(sanitize_redirect_url "$aka_ms_download_link")
Do we know when and how the aka.ms redirects for the dotnet downloads will be updated? @bamurtaugh Do you have a contact to check with?

@sliekens Maybe the script could check if the redirect still points to `azureedge.net` and only in that case run the sanitize step? That might be more robust towards changes of the redirects.

2025-01-07 10:14 UTC, sliekens commented
@chrmarti the dotnet-install.sh script is copied from https://github.com/dotnet/install-scripts/blob/main/src/dotnet-install.sh so I'm not qualified to answer those questions but I think @mmitche can help.

2025-01-07 14:32 UTC, chrmarti commented on src/dotnet/scripts/vendor/dotnet-install.sh
> +        sanitized_redirect_url=$(sanitize_redirect_url "$aka_ms_download_link")
https://github.com/dotnet/core/issues/9671 says about the aka.ms redirects: `We expect these links to be changed in early January.` So this should keep working without modification.

2025-01-07 14:35 UTC, chrmarti commented on src/dotnet/scripts/vendor/dotnet-install.sh
> +        sanitized_redirect_url=$(sanitize_redirect_url "$aka_ms_download_link")
Seeing that you copied https://github.com/dotnet/install-scripts/blob/main/src/dotnet-install.sh, I guess that might see another update?

2025-01-07 14:59 UTC, mmitche commented
Yeah, the install script is going to get another update soon, removing the use of the azureedge domains, at least outside of sanitization. So the script would only try to access the new domains. We're not quite sure yet when we will update old aka.ms links. Once they are updated, then we would remove the sanitization altogether.

2025-01-07 16:20 UTC, chrmarti commented
@mmitche Great, this sounds like we should wait for that imminent update of the install script?

Updating the aka.ms redirects would smooth things out I guess, is there a reason to hold back on that?

2025-01-07 21:05 UTC, chrmarti commented
> Don't forget that script is updated here automatically every Sunday, e.g. see #1236
> 
> I just realized I forgot to bump the version 🤔. Not sure about the semantics of this change either. Probably not a major bump, the behavior didn't change that much and usage remains the same. On the other hand, this change could break users behind corporate firewalls where the CDN is not allowed.

Minor (or patch) might work best since that will be picked up when the devcontainer.json only specifies the major version. There is also an optional lockfile devcontainer-lock.json that pins the exact feature version and checksum and would hold the update back.

I guess we could just run the workflow you mention then (catching up on how we do this): https://github.com/devcontainers/features/actions/workflows/update-dotnet-install-script.yml

2025-01-07 21:16 UTC, sliekens commented
A new minor version makes the most sense to me, I'll do that. I can revert the changes to `dotnet-install.sh` vendor script in this PR if desired, but the changes in the `dotnet-helpers.sh` script are still needed, I wrote those scripts specifically for the devcontainer feature to find the latest version no matter the STS or LTS status.

2025-01-07 21:19 UTC, sliekens commented
I guess I should fix the failing test while I'm at it 🤔.

2025-01-07 22:06 UTC, sliekens commented
@chrmarti I think this work is complete now.

Final changes:
- Fixed failing scenarios which installed the latest dotnet version (now .NET 9) but then tried to run a .NET 8 project
- Bumped dotnet minor version
- Bumped oryx minor version

2025-01-08 07:09 UTC, chrmarti commented
@sliekens Looks great, thanks! We can update the script again when the original changes later this/next week. Adding @gauravsaini04 as a second reviewer.

2025-01-08 07:09 UTC, chrmarti approved these changes

2025-01-08 11:19 UTC, gauravsaini04 approved these changes
All the changes done, LGTM 👍🏻
Thanks @sliekens !

2025-01-08 20:46 UTC, eljog commented
> We can update the script again when the original changes later this/next week

SGTM, @gauravsaini04 let's make a note of that followup

2025-01-08 22:50 UTC, richlander commented on src/dotnet/scripts/vendor/dotnet-install.sh
>      "https://dotnetcli.azureedge.net/dotnet"
Yes, please remove the old URLs.

2025-01-08 22:54 UTC, richlander commented on src/dotnet/scripts/vendor/dotnet-install.sh
> +        sanitized_redirect_url=$(sanitize_redirect_url "$aka_ms_download_link")
Yes.

- We will update the file again in the first half of January. Please grab copies.
- We will be providing users with guidance on how to do freshness checks on when to grab new copies.

Related: https://github.com/dotnet/install-scripts/issues/566

2025-01-09 07:27 UTC, chrmarti commented on src/dotnet/scripts/vendor/dotnet-install.sh
>      "https://dotnetcli.azureedge.net/dotnet"
Seeing there is a PR getting ready on the original, we can just copy that once it is merged. Thanks.

2025-01-09 18:09 UTC, merged

2025-01-10 13:54 UTC, cetinbug commented
For our Azure Functions, we currently use the URL **functionscdn.azureedge.net** to retrieve extension bundles. However, after reviewing the issue, I noticed that there is no specific mention of the subdomain **_functionscdn_** in the migration details. Could you please clarify if this subdomain will also be migrated and, if so, to which domain?

For example, we are getting extension bundles from a url like: _"https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Preview/$EXTENSION_BUNDLE_VERSION"_