desktop-lite: fixed qemu container
devcontainers/features pull request #370
Opened 2022-12-30 21:57 UTC by mrkbac

`pidof` does not work as intended when using, a qemu or rosetta container, `pgrep -x` has the desired effect.

2023-01-03 18:08 UTC, samruddhikhandale requested changes
Left a comment. Besides that LGTM, thanks!

2023-01-03 18:08 UTC, samruddhikhandale commented on src/desktop-lite/install.sh
>      log "Starting \$1."
Can we bump the patch version in here? thanks! 

https://github.com/devcontainers/features/blob/883cf50eb84f2ad3dada748401a5ad6c06bf43b6/src/desktop-lite/devcontainer-feature.json#L3

2023-01-05 11:09 UTC, mrkbac commented
@microsoft-github-policy-service agree

2023-01-05 17:27 UTC, samruddhikhandale approved these changes
Nice!

2023-01-05 17:27 UTC, merged