Add sentinel to terraform feature
devcontainers/features pull request #452
Opened 2023-02-14 01:19 UTC by sdrzazga

Hi.

Based on my feature request #437 I'd like to contribute with this PR to the potential installation of sentinel with the terraform feature.
The description was copied from the corresponding [documentation](https://docs.hashicorp.com/sentinel).
Unfortunately, Hashicorp doesn't release sentinel via GH hence the introduction of a separate function in the `install.sh` to resolve the version from the release URL.

2023-02-14 01:22 UTC, sdrzazga commented
@microsoft-github-policy-service agree

2023-02-14 18:04 UTC, samruddhikhandale requested changes
Looks great, thank you! Left minor comments.

2023-02-14 18:39 UTC, sdrzazga commented on src/terraform/README.md
> +| installSentinel | Install sentinel, a language and framework for policy built to be embedded in existing software to enable fine-grained, logic-based policy decisions. | boolean | false |
Absolute...silly me 🙄

2023-02-14 18:40 UTC, sdrzazga commented on src/terraform/install.sh
> +    sentinel_releases_url='https://releases.hashicorp.com/sentinel'
I agree, this happens when you do changes late in the day.

2023-02-15 02:16 UTC, sdrzazga commented on src/terraform/README.md
> +| installSentinel | Install sentinel, a language and framework for policy built to be embedded in existing software to enable fine-grained, logic-based policy decisions. | boolean | false |
File was reverted

2023-02-15 02:21 UTC, sdrzazga commented on src/terraform/devcontainer-feature.json
>              "default": "latest",
Raised version to 1.2.0

2023-02-15 02:23 UTC, sdrzazga commented
@samruddhikhandale thank you very much for the swift review and comments.
I promise to do better in the future and don't do late-night commits anymore.

2023-02-15 19:59 UTC, samruddhikhandale approved these changes
Awesome, thanks for contributing! ⚡

2023-02-15 19:59 UTC, merged