Update NOTES.md
devcontainers/features pull request #534
Opened 2023-04-28 17:51 UTC by raymond-chetty

#531: Quick document update about UID & GID using 1000 in devcontainer base images.

2023-04-28 17:53 UTC, raymond-chetty commented
Its possible to resolve this if we add a configuration to usermod a username as well as UID & GID. Possibly open a ticket for that.

2023-04-28 20:24 UTC, samruddhikhandale requested changes
Appreciate your help in improving our documentation, thank you! 

Left some minor comments.

2023-04-28 20:24 UTC, samruddhikhandale commented on src/common-utils/NOTES.md
> +## Base Images
```suggestion
## Using with dev container images
```

2023-04-28 20:32 UTC, samruddhikhandale commented
> Looking at how the vscode wizard works, you can't manually type in a UID value only select from an option,

As mentioned in https://github.com/devcontainers/features/issues/531#issuecomment-1524168766,  I believe that's a bug with the wizard. Feel free to open an issue in https://github.com/microsoft/vscode-remote-release/issues

> Looking at how the vscode wizard works, you can't manually type in a UID value only select from an option, it might be better to assume that if UID 1000 exists it belongs to the base image user and that setting changes should all be applied to UID 1000, possibly including UID changes.

> Logic:
> if UID 1000 exists -> mod the user
> if UID X exists -> mod the user (no UID changes)
> else add the user
> 
> This way wizard users will do what they'd expect, modify the base user, assuming we leave the UID & GID 1000 option. Also, manual configurations will be possible with a variety of scenarios either adding or updating a user.

Thanks for sharing your thoughts, it's really helpful. 

We could make this change to the common-utils Feature, however, I am not sure if the logic could become confusing for users ; instead I think a clear error message could navigate them to use different UID/GID to unblock them.
I am happy to help out with the change if people think otherwise.

2023-05-01 19:15 UTC, raymond-chetty commented on src/common-utils/NOTES.md
> +
Thank you for your suggestion. I approve of this correction on behalf of the people of the united states. @PresidentObama :)

2023-05-01 19:16 UTC, raymond-chetty commented on src/common-utils/NOTES.md
> +## Base Images
approved!

2023-05-02 16:55 UTC, samruddhikhandale commented on src/common-utils/NOTES.md
> +## Base Images
Same here!

2023-05-21 12:31 UTC, nanis94 commented
devcontainers:main

2023-05-21 12:42 UTC, nanis94 commented
devcontainers:main

2023-05-21 12:42 UTC, nanis94 commented
devcontainers:main

2023-05-21 12:42 UTC, nanis94 reviewed
devcontainers:main

2023-05-22 19:23 UTC, samruddhikhandale approved these changes
Thanks!

2023-05-22 19:23 UTC, merged