Configure npm proxy when proxy environmentals exist
devcontainers/features pull request #712
Opened 2023-10-03 16:28 UTC by jmedelmann

PR for issue #702 (Node feature does not pick up proxy settings).
Docker automatically sets up proxy environmentals in the container when configured (see https://docs.docker.com/network/proxy/) so usually everything works without additional configuration. An exception is npm, which does not pick up these environmentals and needs to be configured manually. This PR adds the necessary configuration steps.

2023-10-03 16:31 UTC, jmedelmann commented
@microsoft-github-policy-service agree

2023-10-03 16:38 UTC, momohnasirumuri reviewed
Run

2023-10-03 17:37 UTC, samruddhikhandale requested changes
Thanks for contributing this change. 

Currently, this PR is automatically setting proxy if the env variables exist. Instead, can we wrap this logic inside a condition on a new Feature option (say `useProxyConfig:boolean` with default `false`). This way, the users are willingly enabling it as per their needs, and we won't have to worry about folks raising security concerns.

As per https://docs.docker.com/network/proxy/#configure-the-docker-client, adding proxies to `~/.docker/config.json` seems like a manual approach where users are opting into it. So wrapping it inside a Feature option makes sense to me!

2023-10-03 17:38 UTC, samruddhikhandale commented on src/node/devcontainer-feature.json
> +    "version": "1.3.1",
We should bump the minor version when we we add a new Feature option.

2023-10-03 18:03 UTC, jmedelmann commented
> Currently, this PR is automatically setting proxy if the env variables exist. Instead, can we wrap this logic inside a condition on a new Feature option (say `useProxyConfig:boolean` with default `false`). This way, the users are willingly enabling it as per their needs, and we won't have to worry about folks raising security concerns.
> 
> As per https://docs.docker.com/network/proxy/#configure-the-docker-client, adding proxies to `~/.docker/config.json` seems like a manual approach where users are opting into it. So wrapping it inside a Feature option makes sense to me!

These env variables are a kind of standard and almost all programs will use them automatically. If we introduce an additional option for just npm we will create an inconsistent state with no benefit. Note that other programs already use these environmentals. If we want to make them optional it would require to make them optional for the other programs as well.

2023-10-04 22:09 UTC, samruddhikhandale approved these changes
Had a quick chat with the team, turns out the devcontainers/cli supports the automatic support as well. Approving! ✅

2023-10-04 22:09 UTC, merged