[PowerShell]- Fallback method with find_prev_vers_frm_git_tags() implemented
devcontainers/features pull request #926
Opened 2024-03-29 04:46 UTC by gauravsaini04

**Feature name**:
 
 * Powershell
 
 **Description**:
 
 This PR adds the following functionality:
 
 * Added a second installation method using `find_prev_version_from_git_tags()` to install if rate limit for the user accessing GitHub api is reached and installation begins to fail using this fallback method as well..
 
 _Changelog_:
 
 * Updated installation file `install.sh`
 * Updated corresponding tests
 
 **Checklist**:
 
 * [x]   Checked that applied changes work as expected

2024-03-29 21:27 UTC, samruddhikhandale requested changes
One minor comment and we are all set ⚡

2024-03-29 21:27 UTC, samruddhikhandale commented on src/powershell/install.sh
Can we bump the Feature version?

2024-03-31 11:01 UTC, gauravsaini04 commented on src/powershell/install.sh
done 👍

2024-04-02 00:35 UTC, samruddhikhandale approved these changes

2024-04-02 00:35 UTC, merged