Fix rustup-init sha256sum check
devcontainers/features pull request #962
Opened 2024-05-06 23:18 UTC by bearrito

Description:

`sha256sum rustup-init.sha256sum` expects there to be a file name `rustup-init` in the same directory as ` rustup-init.sha256sum`
Instead of messing with the original download path, I just copy the binary to the path where the sha256sum is placed, check it and then delete it. There might be a more efficient way with pipes or similar. 

Tests passing on my machine
```
Test Passed!
🧪 Executing duplicate test for feature 'rust'...
⚠️ Skipping duplicate test for rust because '/home/bstrausser/Git/features/test/rust/duplicate.sh' does not exist.
🧹 Cleaning up 2 test containers...
🧹 Removing container a7c1a0e866f3...
🧹 Removing container 01a2b8770ce2...

  ================== TEST REPORT ==================
✅ Passed:      'rust'
✅ Passed:      'rust_at_pinned_version'

```

closes: https://github.com/devcontainers/features/issues/961

2024-05-06 23:29 UTC, samruddhikhandale requested changes
Left minor comments, appreciate the quick fix 🙌

2024-05-06 23:29 UTC, samruddhikhandale commented on src/rust/install.sh
>      curl -sSL --proto '=https' --tlsv1.2 "https://static.rust-lang.org/rustup/dist/${download_architecture}-unknown-linux-gnu/rustup-init" -o /tmp/rustup/target/${download_architecture}-unknown-linux
Can you bump the patch version for this Feature? Thanks!

https://github.com/devcontainers/features/blob/75602ab7eee94992198fbdb1a3b0d52beb62399a/src/rust/devcontainer-feature.json#L3

2024-05-06 23:29 UTC, samruddhikhandale commented on src/rust/install.sh
> +    rm /tmp/rustup/rustup-init
```suggestion
```

This file would eventually get cleaned up in L195

2024-05-07 00:28 UTC, bearrito commented
@samruddhikhandale Addressed your comments.

2024-05-07 02:56 UTC, bearrito commented
@microsoft-github-policy-service agree

2024-05-07 15:10 UTC, merged