favor correctness by removing `apt update ...` short-circuiting
devcontainers/features pull request #98
Opened 2022-08-16 21:25 UTC by joshspicer

As a follow up from https://github.com/devcontainers/features/issues/94, we've identified a pattern with custom, pre-built images that could cause other features to fail due to stale apt lists.

This change favors correctness over performance by always running `apt update -y` when `apt_get_update()` is called.  This has been kept a function in case further changes want to made made in the future.

2022-08-20 02:00 UTC, jungaretti requested changes

2022-08-22 13:12 UTC, joshspicer commented on src/oryx/install.sh
> +        DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends "$@"
This environment variable tells programs to not let any user-interaction prompts from blocking install operation.  One prompt that blocks a lot is asking for timezone.

2022-08-22 13:13 UTC, joshspicer commented on src/node/install.sh
>      if [ ! -d "/var/lib/apt/lists" ] || [ "$(ls /var/lib/apt/lists/ | wc -l)" = "0" ]; then
thanks!

2022-08-22 17:30 UTC, samruddhikhandale submitted a review, later dismissed

2022-08-23 01:17 UTC, jungaretti approved these changes
LGTM, but you only added `DEBIAN_FRONTEND=noninteractive` to `src/oryx/install.sh`, was that intentional?

2022-08-23 13:17 UTC, merged